name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@v1.6.0
      env:
        HUGO_VERSION: 0.79.1
        TARGET_REPO: 1-100/1-100.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.HUGO_TOKEN }}

